export {default as Cart} from "./Cart/Cart"
export {default as Home} from "./Home/Home"
export {default as Login} from "./Login/Login"
export {default as Pizza} from "./Pizza/Pizza"
export {default as RegisterPage} from "./RegisterPage/Register"